In [27]:
import numpy as np

List = []

A = np.array([1,2,3,4,5,6,7,8,9])
A.shape = (3,3)

B = np.array([0,3,2,5,3,1,2,1,9])
B.shape = (3,3)

arrNum = (-1)
numNum = (-1)

for i in A:
    arrNum += 1
    for j in i:
        numNum += 1
        if numNum>2:
            numNum -= 3
        loca = np.where(A == j)
        if A[loca] <= B[loca]:
            List.append((arrNum,numNum))
             
print(A)
print("")
print(B)
print("")        
        
print(List)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[0 3 2]
 [5 3 1]
 [2 1 9]]

[(0, 1), (1, 0), (2, 2)]
